### ISSUE TITLE
[request] ability to add other teas/infusions in config file

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#10]
other mods add plants and materials that could feasibly be used in making infusions and tonics

would you consider adding a way of adding more infusions through the config file? it wouldnt interfere with the normal feel of the mod, as it would only apply to people that purposefully add things like chamomile infusions and such!

**Comment by RoShioLeo** [comment]
A good idea! I'll take it into consideration.
Flower tea is great, isn't it?

**Comment by majijn** [comment]
it really is! although lately what I've been drinking more than my flower and herbal teas is just green tea with spearmint, with liquorice root as a sweetener ^^

**Comment by RoShioLeo** [comment]
Sounds cool.
By the way, it may take long time to achieve that because the methods now I use can't support it.

**Comment by majijn** [comment]
that's understandable!

its not like I personally need it for a modpack or anything, I just thought it would be a good idea, and giving modpack authors more option may mean your mod gets more downloads!

**Comment by RoShioLeo** [comment]
Thank you very much!

**Comment by Snownee** [comment]
Maybe consider CraftTweaker?

**Comment by nephatrine** [comment]
Would very much love CraftTweaker support to add more drying/fermenting/etc. recipes.

**Comment by RoShioLeo** [comment]
I'm developing new version to support CraftTweaker.
