### ISSUE TITLE
pots reset their uses when set down on as a block and then picked up

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#11]
I only tested the first tea pot and green tea because that's the one I figured out how to get so far
![2018-05-02_19 02 06](https://user-images.githubusercontent.com/18368034/39560323-6a8fa382-4e9d-11e8-85c2-7a9b9585016a.png)
![2018-05-02_19 02 12](https://user-images.githubusercontent.com/18368034/39560324-6aaf0524-4e9d-11e8-91ac-37be0e5d1fda.png)

**Comment by majijn** [comment]
what does agility do? I havent worked it out yet haha

**Comment by majijn** [comment]
also the white porcelain kettle has a weird name while empty!

**Comment by RoShioLeo** [comment]
The 1.12.2 version is upgraded from the 1.10.2 version. It's unchecked, so maybe there are more bugs.

**Comment by RoShioLeo** [comment]
When you have the agility effect, you have chance to dodge any damage.

**Comment by RoShioLeo** [comment]
I found it was the same in 1.10.2 version. I have fixed it in both versions.
