### ISSUE TITLE
Crash on initialize

### ISSUE THREAD

**Issue by Dragnier** [LuoXiao-Wing/Tea-TheStoryOfALeaf#13]
Crashlog: https://paste.dimdev.org/notebufewe.mccrash

**Comment by LuoXiao-Wing** [comment]
That's strange. The file might be incomplete or the version of forge is too high. I'll test it in high version and try to fix it. 
Thank you.

**Comment by RoShioLeo** [comment]
This is a bug of Forgrelin.
https://github.com/shadowfacts/Forgelin/issues/38
