### ISSUE TITLE
Actually additions' farmer skips seedling stage

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#14]
I planted some rice seeds in my farm that was looked over by an AA farmer , and when it harvests it gives 2-3 seeds,and 1 seedling, instead of 3 seedlings

I don't have other farmers  in my pack,but im guessing others may do similar things.

(I havent tested what  it does with the rice in the  paddies, I'll do that later today if I have the time.)

**Comment by RoShioLeo** [comment]
I think it isn't my fault. And it's difficult to solve it, because the way to plant rice is quite different to the vanilla.

**Comment by majijn** [comment]
I think if I tell them about it they'll just say you just have to add support for the farmer
however im not quite certain how that's done =/

edit: it ISNT your fault , but I dont think I can stop the farmer from interacting with my rice on my end, however, what can be done is adding support for the farmer, either by somehow making it ignore the rice, or making it harvest the seedlings properly.

**Comment by majijn** [comment]
tested with seedlings, they get planted on any water , in any biome (if they don't have farmland under the water they pop off however)

edit: I don't think it should  be able to interact with the seedlings , neither planting them or harvesting them. 
I guess harvesting the seeds may be ok? but ...im not sure

**Comment by RoShioLeo** [comment]
I'll change the block type. So it won't be able to be regarded as crop.

**Comment by RoShioLeo** [comment]
I'll finished it in two days.

**Comment by majijn** [comment]
https://github.com/Ellpeck/ActuallyAdditions/tree/master/src/main/java/de/ellpeck/actuallyadditions/api/farmer does this help you at all? I can't really read code =/

**Comment by RoShioLeo** [comment]
It may help.
