### ISSUE TITLE
Add unique Music Disc icons.

### ISSUE THREAD

**Issue by Mike-U5** [LuoXiao-Wing/Tea-TheStoryOfALeaf#16]
Both music discs have exactly the same icon as the "cat".
Please give them unique sprites, so it's easier to tell them apart. 
You can use these quick edits I made if you want:
![record_folk](https://user-images.githubusercontent.com/32613991/43076160-9f79f806-8e83-11e8-96fb-51173392ff64.png)
![record_g20](https://user-images.githubusercontent.com/32613991/43076161-9f96765c-8e83-11e8-9573-d266ab44887a.png)
(No credit needed, except to Mojang for making the originals)

**Comment by RoShioLeo** [comment]
Thanks. I think it's useful.
