### ISSUE TITLE
[Request] Option to disable tea residue acting as bonemeal.

### ISSUE THREAD

**Issue by Mike-U5** [LuoXiao-Wing/Tea-TheStoryOfALeaf#17]
Everything is in the title. I am using a pack where farming is harder, so vanilla bonemeal is disabled.
Alternatively, add an option to reduce the effectiveness of tea residue.

**Comment by RoShioLeo** [comment]
OK. I'll do that this week.

**Comment by Mike-U5** [comment]
Thanks.
