### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by jaz000** [LuoXiao-Wing/Tea-TheStoryOfALeaf#23]
is this TeaStory not working on a server??

https://pastebin.com/nxCKU0FU

that was TeaStory-3.2.2.909-1.12.2.jar
rolled back to TeaStory-3.0.3.701-1.12.2.jar and all is good again ...

**Comment by RoShioLeo** [comment]
There is a bug I confirmed just now. It is to be fixed next version.

**Comment by RoShioLeo** [comment]
The version 3.2.3.930-1.12.2 is available.
