### ISSUE TITLE
When drinking stacked tea, two get consumed

### ISSUE THREAD

**Issue by terrapin47** [LuoXiao-Wing/Tea-TheStoryOfALeaf#24]
When you have more than one tea cup in the same hotbar slot, and drink it, after a short delay, a second one will also get consumed.

**Comment by RoShioLeo** [comment]
What's the mod version? Is it the latest edition? I can't reproduce what you say.

**Comment by terrapin47** [comment]
Sorry, 3.2.4.1028-1.12.2

**Comment by RoShioLeo** [comment]
But I can't actually reproduce it. I think it may be because of mod conflict. Could you provide more information?

**Comment by terrapin47** [comment]
I can reproduce with only TeaStory installed, but it doesn't happen 100% of the time.
![image](https://user-images.githubusercontent.com/13740412/48669256-b673b900-eace-11e8-90e1-cd80fa75599b.png)
For example, here I filled my hotbar with many teas, and I drank one each.  As long as I leave that same hotbar slot selected, there is a chance that after a short delay another one will get consumed.  You can see here, that I have drank two in some slots instead of one.

**Comment by RoShioLeo** [comment]
OK. I reproduced it. And I know how to deal with it. I will fix the bug soon. Thank you!

**Comment by terrapin47** [comment]
Strangely, I seem to still have this issue on 3.2.5-B4.1118-1.12.2, though it appears to happen a bit less often?

**Comment by terrapin47** [comment]
Well no, just rng
![image](https://user-images.githubusercontent.com/13740412/48670391-4ae91600-eae5-11e8-9f59-35ecc3d5b5a5.png)

**Comment by RoShioLeo** [comment]
I‘ll try again next week. It's time that I should go to school.

**Comment by RoShioLeo** [comment]
I think the only way to solve this is to set the max stack size to 1, which is like what Tea the Story used to do.

**Comment by RoShioLeo** [comment]
Just like soup. I don't have better solution.
