### ISSUE TITLE
（多mod）种植水稻导致游戏崩溃

### ISSUE THREAD

**Issue by Xiliusha** [LuoXiao-Wing/Tea-TheStoryOfALeaf#25]
开艮好水稻田后，灌水，插秧（之后还撒了骨粉），游戏会崩溃，可能不会马上崩溃，可能会过一段时间再崩溃，铲除水稻后恢复正常。
！多模组警告！

以下是崩溃报告

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-87.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 12/25/18 3:12 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at roito.teastory.block.XianRicePlant.func_180650_b(XianRicePlant.java:146)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at roito.teastory.block.XianRicePlant.func_180650_b(XianRicePlant.java:146)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: mworld-1-12-2
	All players: 1 total; [EntityPlayerMP['Xiliusha'/119, l='mworld-1-12-2', x=-1863.82, y=65.00, z=-976.90]]
	Chunk stats: ServerChunkCache: 566 Drop: 0
	Level seed: 7064425723844384803
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-465,64,68), Chunk: (at 15,4,4 in -30,4; contains blocks -480,0,64 to -465,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 208342 game time, 250774 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6193 (now: false), thunder time: 105998 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1033559040 bytes (985 MB) / 2365587456 bytes (2256 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 7, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version               | Source                              | Signature                                |
	|:--------- |:-------------------- |:--------------------- |:----------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2                | minecraft.jar                       | None                                     |
	| UCHIJAAAA | mcp                  | 9.42                  | minecraft.jar                       | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | chameleon            | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar            | None                                     |
	| UCHIJAAAA | chineseworkshop      | 1.2.5                 | ChineseWorkshop-1.12.2_1.2.5.jar    | None                                     |
	| UCHIJAAAA | i18nmod              | 1.12.2-1.0.7          | i18nupdatemod-1.12.2-1.0.7.jar      | None                                     |
	| UCHIJAAAA | jei                  | 4.14.3.238            | jei_1.12.2-4.14.3.238.jar           | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.3.39         | Mantle-1.12-1.3.3.39.jar            | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.11.0.106     | TConstruct-1.12.2-2.11.0.106.jar    | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-87               | ImmersiveEngineering-0.12-87.jar    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivepetroleum   | 1.1.9                 | immersivepetroleum-1.12.2-1.1.9.jar | None                                     |
	| UCHIJAAAA | immersivetech        | 1.3.10                | immersivetech-1.12-1.3.10.jar       | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.3          | journeymap-1.12.2-5.5.3.jar         | None                                     |
	| UCHIJAAAA | storagedrawers       | 1.12-5.3.5            | StorageDrawers-1.12.2-5.3.8.jar     | None                                     |
	| UCHIJAAAA | teastory             | 3.2.6-B10.1222-1.12.2 | TeaStory-3.2.6-B10.1222-1.12.2.jar  | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-87.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Xiliusha'/119, l='mworld-1-12-2', x=-1863.82, y=65.00, z=-976.90]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by RoShioLeo** [comment]
具体原因和多模组无关。
相关内容已经由 @forestbat 做了更改。
修订版本发布待本人12月30日学校放假后发布。
