### ISSUE TITLE
[Tick Lag] Tea Table

### ISSUE THREAD

**Issue by Rsslone** [LuoXiao-Wing/Tea-TheStoryOfALeaf#28]
The tea table is causing an abnormal amount of lag when idle. Any insight into this?
~0.5ms/t each table. I've tested placing more, they all do this.

https://i.imgur.com/HUunOIe.png

**Comment by RoShioLeo** [comment]
It seems that you use the old version of the mod.
I have already solve the problem since the version 3.3.0-B22.202-1.12.2.
You could see the [changelog](https://minecraft.curseforge.com/projects/tea-the-story/files/2668918). (Please pay attention to the text in red color.)

**Comment by Rsslone** [comment]
Oh my bad, I guess I missed the update popup. Appreciate it.
