### ISSUE TITLE
Crafttweaker Support error in methode (Suagr - Sugar)

### ISSUE THREAD

**Issue by Fireztonez** [LuoXiao-Wing/Tea-TheStoryOfALeaf#29]
Hello,
I'm interested by your mod, and I look the crafttweaker support and I see at least 2 error, probably in the methode name... I don't know if this is called like that or no in your code, but, this is clearly a typo:
添加无糖配方（三格） Add No Sugar Recipe (3 slots)
mods.teastory.TeaTable.**addNoSuagrRecipe**(leaves, tools, cup, output);

移除无糖配方（三格） Remove No Sugar Recipe (3 slots)
mods.teastory.TeaTable.**removeNoSuagrRecipe**(leaves, tools, cup, output);

Suagr is not a word, I think you porbably want to say Sugar ;)

Fireztonez

**Comment by RoShioLeo** [comment]
I'm sorry. It's my proofreading error.
Now I have corrected it. The word in my code is right.
Thank you.
