### ISSUE TITLE
Hot water

### ISSUE THREAD

**Issue by sjx233** [LuoXiao-Wing/Tea-TheStoryofaLeaf#3]
Drink hot water also "drink" the bottle.

**Comment by LuoXiao-Wing** [comment]
不是会返还一个玻璃瓶的吗？是1.9.4吗？似乎这个版本没测试过热水。还有用英文干什么？

**Comment by LuoXiao-Wing** [comment]
发现原因，1.8.9升级到1.9.4的时候，方法忘改了
