### ISSUE TITLE
希望可以添加炒茶（煮饭）锅CraftTweaker支持，谢谢

### ISSUE THREAD

**Issue by AmalaNever** [LuoXiao-Wing/Tea-TheStoryOfALeaf#32]
很有创意的mod，感谢作者。支持支持！想把这个mod加进整合包，不过遇见一个问题。
希望可以添加炒茶（煮饭）锅CraftTweaker支持。
另外希望这个锅能支持更多的打火石（例如根源魔法的简易点火器，随意作品的灼热打火石等，或者是火焰弹）。

如果作者以后有空的话也许可以联动一下农业工艺（Agricraft），不过农业工艺弃坑了，也可以考虑整到高版本。

再次感谢！

**Comment by RoShioLeo** [comment]
我已经停止更新，一切功能更新都不予以支持。
另外，我退开发圈了。以后不会考虑面向社区的相关开发了。

**Comment by AmalaNever** [comment]
> 我已经停止更新，一切功能更新都不予以支持。
> 另外，我退开发圈了。以后不会考虑面向社区的相关开发了。
哎，太可惜了
