### ISSUE TITLE
在服务器使用茶簸箕的时候出现了一些bug并导致客户端崩溃

### ISSUE THREAD

**Issue by chunye666** [LuoXiao-Wing/Tea-TheStoryOfALeaf#33]
在服务器使用茶簸箕的时候出现了一些问题，当我在发酵模式下向茶簸箕内放入半组绿茶青叶之后再用“shift+左键”快捷放入一组便会导致崩溃，这里是崩溃报告：https://paste.dimdev.org/salawocuqe.rb

**Comment by chunye666** [comment]
服务器版本：CatServer-92b87c7-universal
客户端版本：1.12.2
Forge版本：14.23.5.2855
模组版本：TeaStory-3.3.2-B31.815-1.12.2

**Comment by chunye666** [comment]
需要指出的是，在服务器内如放入茶叶数量超过24个（不含24个），处理时间便会变为负数，在单人模式下没有发现此问题，也没有因为上面的做法而崩溃。

**Comment by RoShioLeo** [comment]
1.12.2 最新版本为 3.3.3-B33.418
CatServer 环境造成的崩溃一概不予修复
