### ISSUE TITLE
关于筛网筛种子有概率得到“幻影种子”的修复方案

### ISSUE THREAD

**Issue by bangbang93** [LuoXiao-Wing/Tea-TheStoryofaLeaf#4]
我服务器遇到这个问题后，我顺着mcbbs的帖子找到了这里的源码，本想Fork后修复发回PR的，但是这里是1.8的，而服务器是1.10.2的，所以不知道代码有多少出入，如果按照这里的1.8的代码看的话，问题出在
https://github.com/LuoXiao-Wing/Tea-TheStoryofaLeaf/blob/57dc05bac02f4f07ffc4f5bd40c872a8dc425823/src/main/java/luoxiaowings/teastory/common/EventLoader.java#L66
luoxiaowings.teastory.common.EventLoader:66
这里用到了一个随机数生成器，若返回值小于0.05F则给玩家种子。
但是问题出在，客户端和服务端会同时运行这个随机数生成器而返回不同的结果。服务器端初始化的随机数生成器和客户端基本是不可能得到相同的种子的，所以得到的基本也是不同的返回结果。于是就可能遇到四种情况
最好的情况是客户端和服务端都落到95%的啥也没有区间内，没有任何问题
第二种情况是客户端和服务端都落到了5%的生成内，也没有任何问题。
第三种情况是客户端95%，而服务端5%，这时候服务端会下发背包更新信息，所以客户端也能得到种子的
第四种情况是服务端95%，而客户端随机到了5%，这时候问题就来了客户端显示出了种子，但是服务端却不这么认为，于是客户端在收到服务端的背包更新数据后，种子就自己消失了。

解决方案很简单，在这里判断是否为服务端，只让服务端运行随机逻辑，然后走第三种情况通过背包更新完成种子的获得。或者使用其他能够让客户端和服务端运行结果确保相同的随机数算法。

**Comment by LuoXiao-Wing** [comment]
哇哦，有劳bangbang93大大了。总觉得这段代码有点问题……←_←，原来是同步问题。通知邮件被归入垃圾邮件一类了……so，今天翻邮箱才发现，正好一个月-_-||。其实这段代码是1.8.9的，打成1.8而已……最近时间紧张，只好放到下次大更新一起了，23333，反正影响也不大。两端的问题是该重视了←_←。
