### ISSUE TITLE
希望能支持新版本😊

### ISSUE THREAD

**Issue by Yiffyi** [LuoXiao-Wing/Tea-TheStoryOfALeaf#4]
比如1.12之类的😀

**Comment by RoShioLeo** [comment]
1.11.2版本的2.0.4版本可以在这里找到（Unofficial）
https://github.com/Team-AbCiv/Tea-ALongStory/releases
其他新版本暂时不考虑，因为本人学业原因

**Comment by RoShioLeo** [comment]
话说1.12.2现在已经支持了
（挖坟？）
