### ISSUE TITLE
stone cup transforms into wooden cup if picked up while empty

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#7]
if I set down a stone cup and pick itup, it loses its texture, andif I set that item down, when I pick it up it turns into an empty wooden cup
![2018-05-01_09 55 35](https://user-images.githubusercontent.com/18368034/39467011-1cfcdf76-4d2c-11e8-9054-6efc5bf92ace.png)
![2018-05-01_09 55 39](https://user-images.githubusercontent.com/18368034/39467012-1d21c52a-4d2c-11e8-9dc1-801bab9ffb35.png)
![2018-05-01_09 55 41](https://user-images.githubusercontent.com/18368034/39467013-1d4340ce-4d2c-11e8-90f8-00050eb6648a.png)
![2018-05-01_09 55 44](https://user-images.githubusercontent.com/18368034/39467014-1d664a4c-4d2c-11e8-9cdd-c4148c281fce.png)

**Comment by RoShioLeo** [comment]
That's truly a problem. Thank you for your feedback.
