### ISSUE TITLE
if you right click the same straw cushion twice, you become stuck and cannot unmount by shifting

### ISSUE THREAD

**Issue by majijn** [LuoXiao-Wing/Tea-TheStoryOfALeaf#9]
I had to break it and put it in a new spot , and sit on that cushion to be able to dismount,
also they seem to leave behind a weird white dot after breaking them 
![2018-05-01_10 27 17](https://user-images.githubusercontent.com/18368034/39466988-00168876-4d2c-11e8-81bd-5a02ea2e10e7.png)

**Comment by RoShioLeo** [comment]
I'll fix it as soon as possible.

**Comment by RoShioLeo** [comment]
The bug in 1.12.2 has been fixed.
